### ISSUE TITLE
Is it possible to release a table of all paired data and scoring results?

### ISSUE THREAD

**Issue by johntzwei** [Yale-LILY/SummEval#9] opened 2020-12-16 14:22 UTC
Dear SummEval authors.

Thank you for your great dataset! I am currently writing up a metric analysis paper, and I hope to use your summarization dataset. I wanted to ask whether you already had some data compiled, and if it was possible to release a pandas dataframe or json file that would contain:

1) Paired data
2) Metric scores (for the 11,000~ outputs for each of the 23 systems).

This would save me a lot of time. Thank you!

**Comment by Alex-Fabbri** [comment] 2020-12-18 14:51
Hi @johntzwei, 

Thanks for your interest! 
For 1) we do not plan to release the paired output. If you run the data_processing/pair_data.py script, you should be able to reproduce the data. Let us know if you run into any issues with the script, and we're more than happy to help there. 

For 2) we do have a jsonl file with the scores but need to organize it before the release. I am a bit backlogged right now but will follow up on this.

**Comment by johntzwei** [comment] 2020-12-20 17:45
Awesome, thank you!

**Comment by Alex-Fabbri** [comment] 2021-01-03 18:05
Sorry for being unable to get this before your deadline! Deadlines and the holidays had me backlogged. We'll upload the scores shortly and also update the paper with the camera-ready version, hopefully in the next week or so.

**Comment by Alex-Fabbri** [comment] 2021-05-05 14:48
Closing this issue since the scores are now available [here](https://drive.google.com/file/d/1d2Iaz3jNraURP1i7CfTqPIj8REZMJ3tS/view?usp=sharing) along with [code](https://github.com/Yale-LILY/SummEval/issues/13#issuecomment-812918298) for reproducing the correlations.

**Closed by Alex-Fabbri** 2021-05-05 14:48 UTC

**Comment by johntzwei** [comment] 2021-05-05 17:13
We ended up using your dataset and the scores you generated for me in our paper. Thank you!
